### PR TITLE
added delete by turn id

### PR DESCRIPTION
**Pull request by mickyarun**
Agent Memory Added a new proc to delete by turn id
When using search tool , we add search as system message to memory and there is no way to delete only this turn id for next conversion, so added method called delete_turn_id by passing turn_id we can delete the particular message from memory

Added all the conditions like empty memory, last message , invalid turn id

### CODE REVIEW

**Comment by mickyarun** [comment]
change  self.current_turn_id = max(msg.turn_id for msg in self.history) to self.current_turn_id = self.history[-1].turn_id

**Comment by KennyVaneetvelde** [comment]
Alrighty @mickyarun I left some comments - once those are fixed & the tests are updated I can approve & merge!

**Review by KennyVaneetvelde — CHANGES_REQUESTED** [review]

**Comment by KennyVaneetvelde** [comment]
@mickyarun Woops, I in fact had not submitted! 🙄 My bad!

**Comment by mickyarun** [comment]
@KennyVaneetvelde I have resolved all the comments

**Pull request merged**
